### ISSUE TITLE
Program to find factorial of a number through iteration.

### ISSUE THREAD

**Issue by CoolRekha** [CoolRekha/Programs#2]
Factorial of a number (denoted by n!) is the product of all numbers from 1 to the number n (1 and n inclusive).
Example: 5! = 1x2x3x4x5 = 120.
Implement it any language.

**Comment by soham2312** [comment]
Can you assign this to me ?
Thank You

**Comment by MakendranG** [comment]
Hi @CoolRekha 

I have worked on this issue and raised a PR https://github.com/CoolRekha/Programs/issues/2

Kindly merge it.
