### ISSUE TITLE
Program to implement selection sort algorithm.

### ISSUE THREAD

**Issue by CoolRekha** [CoolRekha/Programs#20]

**Comment by soham2312** [comment]
can you please assign this task to me?
Thank You

**Comment by harshiitsingh** [comment]
Hey @CoolRekha, please assign this issue.

**Comment by gauriimaheshwarii** [comment]
Hi! Can you please assign this issue to me?

**Comment by Sirsha2468** [comment]
Hi, Can I contribute in this task?
