### ISSUE TITLE
Factorial of a number using recursion.

### ISSUE THREAD

**Issue by CoolRekha** [CoolRekha/Programs#3]
Factorial of a number (denoted by n!) is the product of all numbers from 1 to the number n (1 and n inclusive).
Example: 5! = 1x2x3x4x5 = 120.
Implement it any language.

**Comment by CoolRekha** [comment]
Good luck @Ausaf1 :)

**Comment by Ausaf1** [comment]
@CoolRekha Given PR for this problem solved using two methods -> recursion and optimized recursion(dynamic programming)
